spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://127.0.0.1:5432/open_platform}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false
